### ISSUE TITLE
Study Quality Codes aren't well defined

### ISSUE THREAD

**Issue by remomueller** [sleepepi/heartbeat-data-dictionary#43]
`studyqual`

What do the parts in the domain refer to?
https://sleepdata.org/datasets/heartbeat/variables/studyqual

For example SHHS has a bit more information (but not much)
https://sleepdata.org/datasets/shhs/variables/overall_shhs2

**Comment by remomueller** [comment]
cc @licongcui, @danmobley

**Comment by mrueschman** [comment]
![image](https://cloud.githubusercontent.com/assets/707167/7459739/25f69964-f26c-11e4-8c30-99702626197a.png)

Here's a snippet from the paper form. These longer explanations should be added -- either in the variable description or in the description of domain items.

Assigning @mcailler to make the update.
